{% set version = "0.1.0" %}

package:
  name: xcube_geodb
  version: {{ version }}

source:
  git_url: https://github.com/dcs4cop/xcube-geodb
  git_tag: dzelge_webapi

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - geodb = xcube_geodb.cli.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - geopandas
    - matplotlib-base
    - descartes
    - requests
    - sphinx
    - python-dotenv
    - jupyterlab
    - psycopg2

test:
  imports:
    - xcube_geodb
  #commands:
  #  - xcube --help

about:
  summary: "geodb is a Python package"
  home: https://github.com/dcs4cop/xcube-geodb
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: "geodb is a Python package"
  doc_url: https://xcube_geodb.readthedocs.io
  dev_url: https://github.com/dcs4cop/xcube-geodb

extra:
  recipe-maintainers:
    - dzelge
    - forman
