image: continuumio/miniconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate dcfs-geodb

stages:
    - test
    - deploy

tests:
  stage: test
  script:
    - python -m unittest discover -v
    
production:
  stage: deploy
  script:
  - conda install conda-verify conda-build anaconda-client
  - conda build recipe

  - CONDA_PACKAGE=$(conda build -c conda-forge recipe --output);
  - anaconda -v -t ${ANACONDA_TOKEN} upload "${CONDA_PACKAGE}" -u bcdev --force;
  only:
  - tags