#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

language: bash

os:
  - linux
  - osx
  - windows

before_install:
  - conda install -y -c conda-forge mamba;

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install -y openssl;
      choco install -y miniconda3;
      export PATH="/c/tools/miniconda3/Scripts:$PATH";
      source activate base;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      mamba install -y -c conda-forge postgis
      cd xcube_gen/sql;
      make install;
      cd ../..
    fi

  - conda info -a
  - mamba env create
  - source activate xcube_geodb
  - python setup.py install

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      for f in xcube_geodb/sql/*.sql;
        do
          pgsanity $f;
        done
    fi
  - py.test -v --cov=xcube_geodb
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
  - for nb in notebooks/*.ipynb;
    do
      jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 --output output.ipynb $nb;
    done




