name: xcube_geodb
channels:
  - conda-forge

dependencies:
  # Python
  - python >=3.6
  # Required
  - pip
  - geopandas >=0.5
  - matplotlib-base
  - descartes
  - requests
  - psycopg2
  - pip:
      - fastjsonschema
      - python-dotenv
      - gsconfig-py3
      - testing.postgresql
      - requests_mock
      - ipyauth
  # Exploring
  - jupyterlab
  # Testing
  - pytest >=4.4
  - pytest-cov >=2.6
  - postgis
  - httpretty



