name: dcfs-geodb
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.6
  # Required
  - pip
  - geopandas >=0.5
  - matplotlib-base
  - descartes
  - requests
  - pip:
      - fastjsonschema
      - python-dotenv
      - gsconfig-py3
  # Exploring
  - jupyterlab
  # Testing
  - pytest >=4.4
  - pytest-cov >=2.6
  - psycopg2
  - postgis
  - pip:
    - testing.postgresql
    - requests_mock
  - httpretty



