name: xcube_geodb
channels:
  - conda-forge

dependencies:
  # Python
  - python >=3.6
  # Required
  - pip
  - geopandas
  - matplotlib-base
  - descartes
  - psycopg2
  - requests
  - pip:
      - fastjsonschema
      - gsconfig-py3
      - testing.postgresql
      - requests_mock
      - ipyauth
      - pgsanity
      - python-dotenv
      - requests_mock
  # Exploring
  - jupyterlab
  - nbconvert
  # Testing
  - pytest >=4.4
  - pytest-cov >=2.6
  - httpretty
  # - postgis



