name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - nbsphinx==0.8.6
  - recommonmark
  - nbconvert
  - pandoc
  - pip
  - pip:
      - sphinx_rtd_theme
      - sphinxcontrib.redoc
