name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.0.2
  - nbsphinx==0.8.6
  - recommonmark
  - nbconvert
  - pandoc
  - pip:
      - sphinx_rtd_theme==1.0.0
      - sphinxcontrib.redoc