# This is a basic workflow to help you get started with Actions

name: xcube-geodb-deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - dzelge*
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge
          activate-environment: xcube_geodb
          environment-file: environment.yml

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      # Runs a set of commands using the runners shell
      - name: Install mamba
        shell: bash -l {0}
        run: conda install -c conda-forge mamba