# This is a basic workflow to help you get started with Actions

name: xcube-geodb-deploy

# Controls when the action will run. 
on:
  push:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Determine release name (e.g. v1.0.0, master)
      - name: Set Release Name
        id: releasename
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_REG_USERNAME }}
          password: ${{ secrets.QUAY_REG_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: quay.io/bcdev/xcube-geodb-lab:${{ steps.releasename.outputs.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
