name: Notebooktest xcube-geodb

on: [workflow_dispatch, push]

jobs:
  nb-test:
    runs-on: ubuntu-latest
    env:
      SKIP_PSQL_TESTS: 0
      GEODB_API_SERVER_URL: ${{ secrets.GEODB_API_SERVER_URL }}
      GEODB_AUTH_CLIENT_ID: ${{ secrets.GEODB_AUTH_CLIENT_ID }}
      GEODB_AUTH_CLIENT_SECRET: ${{ secrets.GEODB_AUTH_CLIENT_SECRET }}
      GEODB_AUTH_DOMAIN: ${{ secrets.GEODB_AUTH_DOMAIN }}
      GEOSERVER_SERVER_URL: ${{ secrets.GEOSERVER_SERVER_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          activate-environment: xcube-geodb
          environment-file: environment.yml
      - name: setup xcube-geodb
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python setup.py develop
      - name: install papermill
        shell: bash -l {0}
        run: pip install papermill[all]
      - name: test-notebooks
        shell: bash -l {0}
        working-directory: notebooks
        run: |
          for nb in *.ipynb
          do
            papermill $nb  $(basename -s .ipynb $nb)_out.ipynb
          done