name: Unittest xcube-geodb

on: [workflow_dispatch, push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      SKIP_PSQL_TESTS: 0
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          activate-environment: xcube-geodb
          environment-file: environment.yml
      - name: setup xcube-geodb
        shell: bash -l {0}
        run: |
          conda info
          conda list
          mamba install -c conda-forge postgis
          python setup.py develop
      - name: unittest-xcube-geodb
        shell: bash -l {0}
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
